/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface YTCEthInterface extends ethers.utils.Interface {
  functions: {
    "compound(uint8,address,bytes32,uint256,uint256,address,address,uint256,uint256)": FunctionFragment;
    "uniswapRouter()": FunctionFragment;
    "ytcContract()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "compound",
    values: [
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ytcContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "compound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ytcContract",
    data: BytesLike
  ): Result;

  events: {};
}

export class YTCEth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: YTCEthInterface;

  functions: {
    compound(
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _underlyingAddress: string,
      _yieldTokenAddress: string,
      _amountUnderlying: BigNumberish,
      _deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<[string]>;

    ytcContract(overrides?: CallOverrides): Promise<[string]>;
  };

  compound(
    _n: BigNumberish,
    _trancheAddress: string,
    _balancerPoolId: BytesLike,
    _expectedYtOutput: BigNumberish,
    _expectedBaseTokensSpent: BigNumberish,
    _underlyingAddress: string,
    _yieldTokenAddress: string,
    _amountUnderlying: BigNumberish,
    _deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapRouter(overrides?: CallOverrides): Promise<string>;

  ytcContract(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    compound(
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _underlyingAddress: string,
      _yieldTokenAddress: string,
      _amountUnderlying: BigNumberish,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    uniswapRouter(overrides?: CallOverrides): Promise<string>;

    ytcContract(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    compound(
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _underlyingAddress: string,
      _yieldTokenAddress: string,
      _amountUnderlying: BigNumberish,
      _deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    ytcContract(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    compound(
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _underlyingAddress: string,
      _yieldTokenAddress: string,
      _amountUnderlying: BigNumberish,
      _deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ytcContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
