/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface YTCZapInterface extends ethers.utils.Interface {
  functions: {
    "compoundUniswap(address,uint8,address,bytes32,uint256,uint256,uint256,address,address,uint256,address)": FunctionFragment;
    "compoundZapper(address,uint8,address,bytes32,uint256,uint256,uint256,address,address,bytes,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "compoundUniswap",
    values: [
      string,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "compoundZapper",
    values: [
      string,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BytesLike,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "compoundUniswap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compoundZapper",
    data: BytesLike
  ): Result;

  events: {};
}

export class YTCZap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: YTCZapInterface;

  functions: {
    compoundUniswap(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _deadline: BigNumberish,
      _uniswapContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    compoundZapper(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _zapperCallData: BytesLike,
      _zapperContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  compoundUniswap(
    _ytcContractAddress: string,
    _n: BigNumberish,
    _trancheAddress: string,
    _balancerPoolId: BytesLike,
    _amount: BigNumberish,
    _expectedYtOutput: BigNumberish,
    _expectedBaseTokensSpent: BigNumberish,
    _baseToken: string,
    _yieldToken: string,
    _deadline: BigNumberish,
    _uniswapContract: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  compoundZapper(
    _ytcContractAddress: string,
    _n: BigNumberish,
    _trancheAddress: string,
    _balancerPoolId: BytesLike,
    _amount: BigNumberish,
    _expectedYtOutput: BigNumberish,
    _expectedBaseTokensSpent: BigNumberish,
    _baseToken: string,
    _yieldToken: string,
    _zapperCallData: BytesLike,
    _zapperContract: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    compoundUniswap(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _deadline: BigNumberish,
      _uniswapContract: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    compoundZapper(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _zapperCallData: BytesLike,
      _zapperContract: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    compoundUniswap(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _deadline: BigNumberish,
      _uniswapContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    compoundZapper(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _zapperCallData: BytesLike,
      _zapperContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    compoundUniswap(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _deadline: BigNumberish,
      _uniswapContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    compoundZapper(
      _ytcContractAddress: string,
      _n: BigNumberish,
      _trancheAddress: string,
      _balancerPoolId: BytesLike,
      _amount: BigNumberish,
      _expectedYtOutput: BigNumberish,
      _expectedBaseTokensSpent: BigNumberish,
      _baseToken: string,
      _yieldToken: string,
      _zapperCallData: BytesLike,
      _zapperContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
