/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IYieldTokenCompounding,
  IYieldTokenCompoundingInterface,
} from "../IYieldTokenCompounding";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_trancheAddress",
        type: "address",
      },
    ],
    name: "approveTranchePTOnBalancer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_trancheAddress",
        type: "address",
      },
    ],
    name: "checkTranchePTAllowanceOnBalancer",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_n",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_trancheAddress",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_balancerPoolId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_expectedYtOutput",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_expectedBaseTokensSpent",
        type: "uint256",
      },
    ],
    name: "compound",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IYieldTokenCompounding__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldTokenCompoundingInterface {
    return new utils.Interface(_abi) as IYieldTokenCompoundingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IYieldTokenCompounding {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IYieldTokenCompounding;
  }
}
